# Generated by Django 5.2.6 on 2025-09-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=300)),
                ('car_model', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('milage', models.IntegerField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('colour', models.CharField()),
            ],
        ),
    ]
